name: Build & Release (Windows)

on:
  push:
    tags: ["v*"]        # build every time you push a version tag

jobs:
  build:
    runs-on: windows-latest
    env:
      PYTHONUTF8: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python deps
        run: |
          python -m pip install -r requirements.txt

      # ------------------------------
      - name: Freeze with PyInstaller
        run: |
          pyinstaller --onefile --windowed --name SplitMe ^
                      --icon assets\veetech_icon.ico ^
                      --add-data "assets\veetech_icon.ico;assets" ^
                      --collect-submodules ocrmypdf ^
                      --collect-data ocrmypdf ^
                      run.py


      # 1) fetch & install Inno Setup 6.x
      - uses: svenstaro/setup-innosetup@v2
        with:
            version: "6.2.2" # or omit to get “latest”

        # 2) compile the installer
      - name: Build installer (Inno Setup)
        run: |
            iscc build\SplitMe.iss /dVERSION=${{ github.ref_name }}
 

      # installer appears at build/Output/*.exe
      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/SplitMe.exe
            build/Output/SplitMe-Setup-*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
